# Generated by Django 5.0.1 on 2025-03-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
